from collections import Counter
array = ['ENMOUTH EMBLED LACHACHILD GROUBTED AT THE JOHNS ARE ABLE TO AMBIOUS ATTLE ATTLE ATTLE ATTEMPTS ATLED AT THE HUDDERSTOOD OF THE JOSEPH THAN HUGH THROUGH THAN THEM',
'CNHAMINA DUAL HNUH A HDUH A LIHNUH HRHU HNGEH HUH A DIHUH A HMUH HMUH HMUH HMUH A HMUH HMUH A HMUH A HDUH A HDUH A HDU HDUH A HMUH A HDU HDUAL HNU HDUAL H A HDUAL HUOT A HNU HUDUAL HDUAL HUALK AUDU',
'ESAUTO ALI OSHADO ACTUALOFICTAL SPIOLDUALIZO PIUDO ACTUALIÚPIDO COMO PIÚ SOCIAL HUCTUAL HUACTUALIUROUXADOUALIVOUEVOZUEVODOUEVOZODOUEVOZODOODOUEVOZOICO',
'FAاگه بگونها من کولون که که که کهالیوا الکه کولوا که الکه الکه روداه کولاسال بودود های کال کولادی که رادیدواکن دایر کنوادهای تادادادهای اداداد این کنواکنو اینده',
'IEA SPAPAPIPIODUDUABHUDUAG ANALIÚ ALEIDEO SÉ AN CHUDUIO SÚDUDUIO SÍOUD SÚ AN CHUDUIOUD AN CHUDUIOUD SÍOUD AN HUDUIOUD AN HUDUIOUD AN HUADDUIOUD AN HUAGHDUIOUD AN HUAGHUDDD HUAGHUD',
'CNHA JOU AMAL HUA CHU CHOMU HNU CHU CHU CHAU HMU CHU HMU HMU CHU HMU HMU CHAU CHAU HMU CHAUHMU CHU CHAU CHAU HMU HMU HMU CHU HMU CHAU CHU HMU CHUAU CHAU CHAU HMUAU CHU CHUHMU TIAU CHU HUHTANU CHUHMU CHUAUHMU CHUAU HTANU JUA CHUAUA JUA JUANUA HMUA JUA HTANUA JUA HTANUA JUA HTANUA JUA JUA',
'PLA JULIU EMBABAJO JAQUEJO SOMPODZIEJU JUDU AGDUCZUJO JUGODJU JUDZOBROJUDJU JUCZDJOJU AJUDJUCZDUJO JUGORDU JO JUDAJO EM JUDAJOROJO JUDZOJOROJO JODJOJOJOJOROJUDJUDJUJOJOJOJOJÓR JUGODRODJUDJUDJUKUJUJUJUJUJUJUJUJUJUJUJUJUJÓRÓJUDOVOLJU',
'FRAUGHTS HUI QUI QUIDE QUATRE HUIT HUDS HUGHES QUI علی که ولی که خنده خنده خنده خنده خنده خنده خنده خواه']
array2 = []
for item in array:
  substring = item[:2]
  array2.append(substring)

print(Counter(array2))
print(len(array2))